language: python
python:
  - "2.7"
#  - "2.6"
#  - "3.2"
#  - "3.3"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: nosetests tests/*  --with-coverage --cover-html --cover-package=pype
after_success: coveralls